# Generated by Django 3.0 on 2021-05-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecom', '0035_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Discount50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount50', models.CharField(max_length=10, null=True)),
                ('amount50', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(related_name='discount_50', to='pay.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Discount30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount30', models.CharField(max_length=10, null=True)),
                ('amount30', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(related_name='discount_30', to='pay.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Discount20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount20', models.CharField(max_length=10, null=True)),
                ('amount20', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(related_name='discount_20', to='pay.Discount')),
            ],
        ),
    ]
