# Generated by Django 3.0 on 2021-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount20',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='discount30',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='discount50',
            name='customer',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount20',
            field=models.ManyToManyField(related_name='discount_20', to='pay.Discount20'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount30',
            field=models.ManyToManyField(related_name='discount_30', to='pay.Discount30'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount50',
            field=models.ManyToManyField(related_name='discount_50', to='pay.Discount50'),
        ),
    ]
