# Generated by Django 3.0 on 2021-05-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20210527_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount20',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount20',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount20'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount30',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount30',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount30'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount50',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount50',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount50'),
            preserve_default=False,
        ),
    ]
