# Generated by Django 3.0 on 2021-05-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_delete_discount'),
        ('pay', '0004_auto_20210527_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='ecom.Customer'),
        ),
    ]
