# Generated by Django 3.0 on 2021-05-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_delete_discount'),
        ('pay', '0006_auto_20210527_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount20',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount30',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount50',
        ),
        migrations.AddField(
            model_name='discount20',
            name='dicount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount'),
        ),
        migrations.AddField(
            model_name='discount30',
            name='dicount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount'),
        ),
        migrations.AddField(
            model_name='discount50',
            name='dicount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.Discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='ecom.Customer'),
        ),
    ]
