# Generated by Django 3.0 on 2021-05-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_delete_discount'),
        ('pay', '0008_auto_20210527_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount20',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discount20',
            name='discount20',
        ),
        migrations.RemoveField(
            model_name='discount30',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discount30',
            name='discount30',
        ),
        migrations.RemoveField(
            model_name='discount50',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discount50',
            name='discount50',
        ),
        migrations.AddField(
            model_name='discount20',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
        migrations.AddField(
            model_name='discount30',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
        migrations.AddField(
            model_name='discount50',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
