# Generated by Django 3.0 on 2021-05-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0035_delete_discount'),
        ('pay', '0009_auto_20210529_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount50', models.IntegerField(blank=True, default=0, null=True)),
                ('amount30', models.IntegerField(blank=True, default=0, null=True)),
                ('amount20', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='discount30',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='discount50',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Discount20',
        ),
        migrations.DeleteModel(
            name='Discount30',
        ),
        migrations.DeleteModel(
            name='Discount50',
        ),
    ]
