# Generated by Django 3.0 on 2021-05-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0036_data_discount'),
        ('pay', '0010_auto_20210529_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list12', to='ecom.Customer'),
        ),
    ]
