# Generated by Django 3.0 on 2021-05-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0037_auto_20210529_1812'),
        ('pay', '0011_auto_20210529_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='accumulationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulatedPoints', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Customer')),
            ],
        ),
    ]
