# Generated by Django 3.1 on 2021-04-11 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('data_ordered', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('Streetstlye', 'Streetstlye'), ('Craft', 'Craft'), ('Fashion', 'Fashion'), ('Denim', 'Denim'), ('Lifestyle', 'Lifestyle')], max_length=200, null=True)),
                ('categories', models.CharField(choices=[('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Streetstlye', 'Streetstlye'), ('Lifestyle', 'Lifestyle'), ('DIY&Craft', 'DIY&Craft')], default='null', max_length=200, null=True)),
                ('images1', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('detail1', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Bag', 'Bag'), ('Shoes', 'Shoes'), ('Watches', 'Watches')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tag', models.CharField(choices=[('HOODIE', 'HOODIE'), ('SHIRT', 'SHIRT'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Denim', 'Denim'), ('Streetstyle', 'Streetstyle'), ('Crafts', 'Crafts')], max_length=200, null=True)),
                ('images1', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('images2', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('images3', models.ImageField(blank=True, default='null', null=True, upload_to='')),
                ('widthS', models.FloatField(null=True)),
                ('heightS', models.FloatField(null=True)),
                ('sleeveS', models.FloatField(null=True)),
                ('shoulderS', models.FloatField(null=True)),
                ('widthM', models.FloatField(null=True)),
                ('heightM', models.FloatField(null=True)),
                ('sleeveM', models.FloatField(null=True)),
                ('shoulderM', models.FloatField(null=True)),
                ('widthL', models.FloatField(null=True)),
                ('heightL', models.FloatField(null=True)),
                ('sleeveL', models.FloatField(null=True)),
                ('shoulderL', models.FloatField(null=True)),
                ('widthXL', models.FloatField(null=True)),
                ('heightXL', models.FloatField(null=True)),
                ('sleeveXL', models.FloatField(null=True)),
                ('shoulderXL', models.FloatField(null=True)),
                ('widthXXL', models.FloatField(null=True)),
                ('heightXXL', models.FloatField(null=True)),
                ('sleeveXXL', models.FloatField(null=True)),
                ('shoulderXXL', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shiping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_complete', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.orderitem')),
            ],
        ),
    ]
