# Generated by Django 3.1 on 2021-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20210412_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='order',
        ),
    ]
