# Generated by Django 3.1 on 2021-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20210413_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
