# Generated by Django 3.1 on 2021-04-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_dataorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='order',
        ),
        migrations.RemoveField(
            model_name='data',
            name='order_item',
        ),
        migrations.AddField(
            model_name='data',
            name='dataOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.dataorder'),
        ),
        migrations.AddField(
            model_name='dataorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
