# Generated by Django 3.1 on 2021-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20210415_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataorder',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
