# Generated by Django 3.1 on 2021-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20210415_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dataorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='dataorder',
            name='size',
        ),
        migrations.AddField(
            model_name='data',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
