# Generated by Django 3.1 on 2021-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20210415_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataorder',
            name='complete',
        ),
        migrations.AddField(
            model_name='data',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
