# Generated by Django 3.1 on 2021-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20210416_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceFilter',
            field=models.IntegerField(null=True),
        ),
    ]
