# Generated by Django 3.1 on 2021-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_auto_20210424_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=1),
        ),
    ]
