# Generated by Django 3.1 on 2021-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_auto_20210424_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount20',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='amount30',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='amount50',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount20',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount30',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
