# Generated by Django 3.1 on 2021-05-01 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_remove_oldpassword_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldpassword',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
