# Generated by Django 3.1 on 2021-05-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('th', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.customer')),
            ],
        ),
    ]
