# Generated by Django 3.0 on 2021-05-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_auto_20210509_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('data_create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
