# Generated by Django 3.0 on 2021-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0031_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=8, null=True),
        ),
    ]
