# Generated by Django 3.0 on 2021-05-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0032_bill_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total_profit',
        ),
    ]
