# Generated by Django 3.0 on 2021-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0033_remove_income_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
