# Generated by Django 3.0 on 2021-05-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0034_auto_20210513_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
