# Generated by Django 3.0 on 2021-05-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0036_data_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
