# Generated by Django 3.0 on 2021-05-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0037_auto_20210529_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
