# Generated by Django 3.0 on 2021-06-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0039_auto_20210601_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='growth_total_cost',
            new_name='growth_total_profit',
        ),
    ]
