# Generated by Django 3.0 on 2021-06-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0040_auto_20210601_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='growth_total_profit',
            new_name='growth_profit',
        ),
    ]
