# Generated by Django 3.0 on 2021-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0041_auto_20210601_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='growth_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
