# Generated by Django 3.0 on 2021-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_auto_20210601_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='null', max_length=2000),
        ),
    ]
