# Generated by Django 3.0 on 2021-06-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0045_auto_20210606_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiping',
            name='order',
        ),
        migrations.AddField(
            model_name='shiping',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.DataOrder'),
        ),
    ]
