# Generated by Django 3.0 on 2021-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0047_customer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
