# Generated by Django 3.0 on 2021-06-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0048_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceFilter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
