# Generated by Django 3.0 on 2021-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
