# Generated by Django 3.0 on 2021-05-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0034_auto_20210513_2056'),
        ('chat', '0002_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
            ],
        ),
    ]
