# Generated by Django 3.0 on 2021-06-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_auto_20210601_1200'),
        ('chat', '0004_auto_20210515_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='ecom.Customer'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nameRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
    ]
