# Generated by Django 3.0 on 2021-06-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_auto_20210601_1200'),
        ('chat', '0006_auto_20210601_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='ecom.Customer'),
        ),
    ]
