# Generated by Django 3.0 on 2021-05-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='dateTimeGift',
            field=models.DateTimeField(),
        ),
    ]
